Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" 

  config.vm.provider "virtualbox" do |vb|
    # Configuraciones específicas de VirtualBox
    vb.memory = "1024"  
    vb.cpus = 2         
  end

  config.vm.network "private_network", ip: "192.168.33.11"
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y build-essential libssl-dev git unzip

    git clone https://github.com/wg/wrk.git
    cd wrk
    make
    cp wrk /usr/local/bin
  SHELL
end

